baseURL = "https://adnair2024.github.io/blog/"
languageCode = "en-us"
title = "Ash's Blog"
theme = "brewm"

# Important for subdirectory deployment:
relativeURLs = false


[params.home]
  featuredListing = ['categories', 'tags']
  disableSlide = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10