baseURL = "https://adnair2024.github.io/blog/"
languageCode = "en-us"
title = "Ash's Blog"
theme = "brewm"

# Important for subdirectory deployment:
relativeURLs = false
uglyURLs = true
canonifyURLs = true


[params.home]
  featuredListing = ['categories', 'tags']
  disableSlide = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30